
# SEO settings
title: "Khons"
title2: "Blog" # default: ""
description: "Sinan Keskin aka Khons blog."
keywords: "Blog about C#, Java, Ruby"
url: http://kesk.in # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-102614012-1
repo: http://github.com/sinankeskin/sinankeskin.github.io
disqus_shortname: "kesk-in"
twitter_username: "_khons"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Sinan Keskin"
  job      : "Freelance Developer"
  bio      : "C#, Java, Ruby"
  thumb    : assets/images/author.jpg
  email    : sinan@kesk.in
  url      : http://kesk.in
  github   : http://github.com/sinankeskin
  twitter  : http://twitter.com/_khons
  facebook : https://www.facebook.com/developer.khons
  linkedin : https://www.linkedin.com/in/sinan-keskin-a3524732

# social settings
og_locale: "tr_TR"
twitter_card: "summary_large_image"
twitter_site: "@_khons"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : hakkimda
    title: Hakkımda
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
