
# SEO settings
title: "Khons"
title2: "Blog" # default: ""
description: "Sinan Keskin aka Khons blog."
keywords: "Blog about .NET, C#, Java, Ruby"
url: http://sinankeskin.github.io/ # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "heiswayi"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Sinan Keskin"
  job      : "Freelance Developer"
  bio      : ".NET, Java, Ruby."
  thumb    : /images/author.jpg
  email    : sinan@kesk.in
  url      : http://sinankeskin.github.io
  github   : http://github.com/sinankeskin
  twitter  : http://twitter.com/_khons
  facebook : https://www.facebook.com/profile.php?id=1257583160
  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "tr_TR"
twitter_card: "summary_large_image"
twitter_site: "@_khons"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
